### ISSUE TITLE
Kube Bench Adapter has wrong Summary Numbers

### ISSUE THREAD

**Issue by fjogeleit** [kubernetes-sigs/wg-policy-prototypes#80]
The created `kube-bench` ClusterPolicyReport in my cluster has the following Summary

```bash
kubectl get cpolr kube-bench

NAME         PASS   FAIL   WARN   ERROR   SKIP   AGE
kube-bench   63     13     43     0       0      105s
```

But the ClusterPolicyReport has only 23 results in summary:

<img width="1510" alt="Bildschirmfoto 2021-06-29 um 09 45 00" src="https://user-images.githubusercontent.com/16627596/123757911-b7903800-d8be-11eb-936c-8bce9788dc2b.png">

**Comment by mritunjaysharma394** [comment]
Hi @fjogeleit, I am not sure if I am able to regenerate this issue. Checking it locally, the summary number seems to be fine however, I would like if you can detail it out more on what specifically is the issue? Thanks for your time and your contribution!

**Comment by fjogeleit** [comment]
Hey, I am running the Kube Bench Adapter on a local minikube cluster on my local laptop. The summaries are like above much heigher then the actual number of PolicyReportResults in the ClusterPolicyReport.

**Comment by mritunjaysharma394** [comment]
Okay, I will take a closer look at it tomorrow and will come with updates, thanks for bringing this to notice!

**Comment by fjogeleit** [comment]
Sure, let me know if you need more information

**Comment by mritunjaysharma394** [comment]
Hi @fjogeleit , I guess, there's a slight confusion maybe, if you will check the [struct](https://github.com/aquasecurity/kube-bench/blob/14aef408e8a7871732423dafe5764bd551bc7f18/check/controls.go#L45) defined in `kube-bench`'s check package, you will find an additional `Total` of type `Summary` and Summary is defined [here](https://github.com/aquasecurity/kube-bench/blob/14aef408e8a7871732423dafe5764bd551bc7f18/check/controls.go#L72). 

Now as I can see in your code, we are using `Summary` directly [here](https://github.com/fjogeleit/policy-reporter/blob/205c4238ef94fb6c7e0140c1d4da3b01e04b0971/pkg/api/model.go#L48) while in the mapping we use in Kube-Bench Adapter, it is `Totals.Summary` and not `Summary` directly and that's why what we see here is a mismatch of numbers.

While your UI maybe getting the `Summary` of particular `Rule` only (very likely the last one), our adapter gets the `Summary` of all the `Rules` and that's why maybe we see this difference in results? Please reach out if you have any further things to clarify, thanks a lot!

**Comment by fjogeleit** [comment]
Okay, I understand. Thanks for clarifying. I was just confused if I get a summary of 13 Fails but only have 5 failed Results, how can I fix or check the rest?

In Kyverno the Summary is number of existing Results in the Report. So I was wondering why they are something different in this adapter. @JimBugwadia what do you think?

**Comment by JimBugwadia** [comment]
So, the kube-bench `Totals` (https://github.com/aquasecurity/kube-bench/blob/14aef408e8a7871732423dafe5764bd551bc7f18/check/controls.go#L43) are higher than the actual result entries derived from the `Controls`? Do we know why? Is there data in the `Controls` that we are not able to translate to a policy result?

**Comment by JimBugwadia** [comment]
It would be interesting to look at the raw kube-bench report and compare it with the policy report to see if there was anything lost in translation.

**Comment by mritunjaysharma394** [comment]
Hi @JimBugwadia and @fjogeleit , I tried creating a raw kub-bench using their "in-cluster" [documentation ](https://github.com/aquasecurity/kube-bench#quick-start)(using a different job name but the job.yaml remains the same ) and in parallel ran our kube-bench adapter. 
I am attaching the outputs of the same and both look pretty similar, only difference observed was in the warnings which can be natural since we are then creating it using policy report. 

1. Summary of kube-bench adapter
![Screenshot from 2021-07-01 00-57-51](https://user-images.githubusercontent.com/45476902/124020700-3f358e00-da08-11eb-99b7-6f4327766f37.png)

2. Summary of raw kube-bench
![Screenshot from 2021-07-01 00-58-05](https://user-images.githubusercontent.com/45476902/124020724-49578c80-da08-11eb-9fea-29340dcb1528.png)

Thanks a lot for your response and looking forward for further discussion!

**Comment by JimBugwadia** [comment]
Thanks @mritunjaysharma394!  And, how many entries to you see in results array? Does it equal 122 as seen in the totals?

**Comment by JimBugwadia** [comment]
@mritunjaysharma394 - any updates on the prior question?

**Comment by mritunjaysharma394** [comment]
The difference was there only in the WARN and on further examinations, it was found that we are missing `controlplane` , other than that, all things worked fine in both of them, i guess this` controlplane` is being missed due to some problems maybe in `job.yaml`(as they were embedded and we might need to update them, not sure about it) ?.

![Screenshot from 2021-07-08 20-05-26](https://user-images.githubusercontent.com/45476902/125653234-65063d1b-55a6-4f37-a1a0-2e9e28c236ec.png)

**Comment by JimBugwadia** [comment]
@mritunjaysharma394 - any updates on this?

**Comment by JimBugwadia** [comment]
@fjogeleit @mritunjaysharma394 - what are the next steps here?
